### PR TITLE
Delay gtscript function symbol resolution until generation

### LINKED ISSUE #202: Push off gtscript.function external symbol resolution time until stencil generation time
In fv3core, for various reasons, we manually invoke `gtscript.stencil(definition=stencil_func, ...)` at the time of first usage, since we are still setting up the backend and rebuild flag at run-time in the tests. However, using externals that are defined later than module-load-time are not working, since `gtscript.function` tries to resolve the externals at load time.

I propose changing the decorator to register functions, and delay the symbol resolution until the time the stencil inlines the call.

### PR DESCRIPTION
**Pull request by jdahm**
Changes `gtscript.function` to only add the `_gtscript_` attribute (and set to `None`), delaying the annotation until later.

Resolves #202.

### CODE REVIEW

**Comment by jdahm** [comment]
Here is the test I used when creating this PR. I'm not sure how best to incorporate this sort of test into the current infrastruture.

```python
import gt4py.gtscript as gtscript
import gt4py.storage as gt_storage

import numpy as np


@gtscript.function
def func(field_in):
    return field_in * constant


def stencil(field_in: gtscript.Field[float], field_out: gtscript.Field[float]):
    with computation(PARALLEL), interval(...):
        field_out = func(field_in)


if __name__ == "__main__":
    build_info = {}

    backend = "numpy"
    shape = (3, 3, 3)

    constant = 1.0
    stencil_call = gtscript.stencil(backend="numpy", definition=stencil, build_info=build_info, rebuild=True)

    field_in = gt_storage.zeros(
        backend=backend, dtype=np.float64, shape=shape, default_origin=(0, 0, 0)
    )
    field_out = gt_storage.zeros(
        backend=backend, dtype=np.float64, shape=shape, default_origin=(0, 0, 0)
    )

    stencil_call(field_in, field_out)
```

**Comment by jdahm** [comment]
I'm not certain that pulling externals into `GTScriptParser.annotate_definition` is quite what the original author had in mind, so I'm open to other suggestions. What complicates this is the imported function symbols like `fwd_diff` from
```python
class TestHorizontalDiffusionSubroutines(gt_testing.StencilTestSuite):
    ...
    def definition(u, diffusion, *, weight):
        from __externals__ import fwd_diff

        with computation(PARALLEL), interval(...):
            laplacian = lap_op(u=u)
            flux_i, flux_j = fwd_diff(field=laplacian)
            diffusion = u[0, 0, 0] - weight * (
                flux_i[0, 0, 0] - flux_i[-1, 0, 0] + flux_j[0, 0, 0] - flux_j[0, -1, 0]
            )
```

Is this something we need to support?

**Comment by jdahm** [comment]
This PR is ready for a review now.

**Comment by egparedes** [comment]
I would like to make sure that I understand the issue here before actually reviewing the implementation, because after reading the motivating example, I think there is no need at all for this fix. If I understood it correctly, the problem in the following examples is that `constant` has not yet been defined so the function definition does not work.
```python
import gt4py.gtscript as gtscript
import gt4py.storage as gt_storage

import numpy as np


@gtscript.function
def func(field_in):
    return field_in * constant


def stencil(field_in: gtscript.Field[float], field_out: gtscript.Field[float]):
    with computation(PARALLEL), interval(...):
        field_out = func(field_in)


if __name__ == "__main__":
    build_info = {}

    backend = "numpy"
    shape = (3, 3, 3)

    constant = 1.0
    stencil_call = gtscript.stencil(backend="numpy", definition=stencil, build_info=build_info, rebuild=True)

    field_in = gt_storage.zeros(
        backend=backend, dtype=np.float64, shape=shape, default_origin=(0, 0, 0)
    )
    field_out = gt_storage.zeros(
        backend=backend, dtype=np.float64, shape=shape, default_origin=(0, 0, 0)
    )

    stencil_call(field_in, field_out)
```

But as far as I know, it would be enough to define the `constant` value as a regular external and provide the actual value at compilation time. Something like this:

```python
@gtscript.function
def func(field_in):
    from __externals__ import constant

    return field_in * constant

...

    stencil_call = gtscript.stencil(backend="numpy", definition=stencil, build_info=build_info,
                                    externals={'constant': -1.11}, rebuild=True)

```

**Comment by jdahm** [comment]
@egparedes This covers one usage of externals, but not the "automatically capturing" case.

You are correct: it is good behavior that when `from __externals__ import level` is present, that the value passed overrides the nonlocal in the closure, e.g.
```python
level = 1
@gtscript.stencil(backend="numpy")
def stencil(field_in: gtscript.Field[float], field_out: gtscript.Field[float]):
    from __externals__ import level
    with computation(PARALLEL), interval(0, level):
```
Without the `from __externals__ import level`, then `level=1` in the stencil.

However:
1. This still seems like a bug, or at least very non-parallel behavior: `gtscript.stencil` nonlocals are captured at compilation time, but `gtscript.function` externals are resolved when the decorator is executed?
2. Not a scalable solution: In our code we have hundreds of these types of nonlocals, and passing them all at stencil compilation time would be tedious. In fact we have functions calling functions calling functions.
3. Please tell me if otherwise, but as far as I can tell merging this change does not hinder any workflow.
4. We already really rely on this in our code :)

**Comment by jdahm** [comment]
Closing this for now.

**Pull request closed without merging**
