### PR TITLE
Use CUDA 11.2 in OCI image

### LINKED ISSUE #812: Missing public key
Saw this on a bors-ng run today on daint:

```
#6 [2/6] RUN apt-get update -qq && apt-get install -qq -y --no-install-recommends     strace     build-essential     cuda-toolkit-10.1     tar     wget     curl     ca-certificates     zlib1g-dev     libssl-dev     libbz2-dev     libsqlite3-dev     llvm     libncurses5-dev     libncursesw5-dev     xz-utils     tk-dev     libffi-dev     liblzma-dev     python-openssl     libreadline-dev     git     htop &&     rm -rf /var/lib/apt/lists/*
#6 sha256:2d8aa4a9ff98ea0a531f61771fbffd1cfbd6b25b0df1d222c5d9eed537c6648b
#6 4.901 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#6 4.901 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
#6 ERROR: executor failed running [/bin/sh -c apt-get update -qq && apt-get install -qq -y --no-install-recommends     strace     build-essential     cuda-toolkit-10.1     tar     wget     curl     ca-certificates     zlib1g-dev     libssl-dev     libbz2-dev     libsqlite3-dev     llvm     libncurses5-dev     libncursesw5-dev     xz-utils     tk-dev     libffi-dev     liblzma-dev     python-openssl     libreadline-dev     git     htop &&     rm -rf /var/lib/apt/lists/*]: exit code: 100
```

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Upgrade the OCI image environment to CUDA 11.2.

Resolves #812.

### CODE REVIEW

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
@DropD or someone else with access. Can you look into the failure here?

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Comment by havogt** [comment]
bors try

**Comment by havogt** [comment]
bors try

**Comment by havogt** [comment]
bors try

**Comment by havogt** [comment]
bors try

**Review by havogt — APPROVED** [review]

**Pull request merged**
