### PR TITLE
bug[next]: Fix astype for local fields

### PR DESCRIPTION
**Pull request by SF-N**
Now calling  `_map` additionally.

~~Some dace tests are skipped because they are failing:~~
- ~~dace_itir: will probably be deprecated soon?~~
- ~~dace_gtir: this feature is missing~~

### CODE REVIEW

**Comment by edopao** [comment]
#1753 will remove the `dace_itir` backend, and this should solve the first problem. I am in favor of merging #1753, I have added @havogt as reviewer.

I will push a fix for the second problem, in `dace_gtir` backend.

**Comment by SF-N** [comment]
> I will push a fix for the second problem, in `dace_gtir` backend.

Thanks @edopao, the test now also passes with dace_gtir.

**Comment by edopao** [comment]
OK from my side for the dace lowering.

**Comment by edopao** [comment]
The `dace.itir `backend has been deleted in main branch, so I have removed the `pytest.skip` in the new test case.

**Review by havogt — APPROVED** [review]
lgtm

**Pull request merged**
