### PR TITLE
fix[cartesian]: While loops inside conditions

### PR DESCRIPTION
**Pull request by romanc**
## Description

This is a follow-up from PR https://github.com/GridTools/gt4py/pull/1630. It combines two things

1. In `oir_to_npir`, we fix conditional `while` loops in `numpy` backend. After PR 1630 these were stuck under certain conditions. Tests coverage extended.
2. In `gtir_to_oir`, we cleaned up the now unused `mask` parameter, which was pre-PR 1630 needed to pass down the mask information. With PR 1630 we actually removed the need for that parameter to be passed along because we properly nest the nested statements.

## Requirements

- [x] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

### CODE REVIEW

**Review by FlorianDeconinck — APPROVED** [review]
LGTM

This comes because the OIR was writing itself as a vector-logic IR (presumably to follow `numpy` implementation). But now, conditions are properly nested and the vector-way of masking per operation is left to NPIR

**Comment by romanc** [comment]
@egparedes Enrique would you have time to kick off the CSCS test suite and to do another review? Thanks in advance :pray:

**Comment by egparedes** [comment]
cscs-ci run

**Review by twicki — APPROVED** [review]
LGTM,

This removes the extra code that was around combining masks that should now no longer be needed because nesting happens directly.

**Comment by romanc** [comment]
Thanks everybody for their reviews. @egparedes we are happy to merge now whenever is convenient for you.

**Pull request merged**
