### PR TITLE
Cleanup passes and add some documentation

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Mainly adds documentation to better understand how the passes work.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [x] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [x] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Review by egparedes — APPROVED** [review]
The PR looks good.  Thanks for taking time to polish and document this module.

I knew that this code was rushed out, but looking at it again after a long time makes it too evident. There are several non-optimal decisions here, but defining the `apply()` methods in the passes as regular instance methods instead of classmethods that create the pass instance and  automatically run it, is definitely wrong :facepalm:, although this is probably out of the scope of this PR.

**Comment by jdahm** [comment]
> defining the apply() methods in the passes as regular instance methods instead of classmethods that create the pass instance and automatically run it, is definitely wrong 🤦

Yes, I was wondering about those :)

I would like to make that change part of this PR. Let's make them stateless.

**Comment by jdahm** [comment]
@egparedes @DropD This is ready to go. One of you might want to check my changes in `analysis_setup.py`.

**Review by egparedes — COMMENTED** [review]
It looks good. One minor question: why the `apply()` methods do not longer return the `TransformData` as before?

**Comment by jdahm** [comment]
I didn't think they need to, since they only change attributes of `transform_data`. The only thing a pass cannot do then is replace `transform_data` with a new object inside its scope. However, I didn't think that would need to happen, and is counter to the idea of a "pass" on an IR.

**Comment by egparedes** [comment]
Yes, I agree, passes don't need to return the data. It is just a matter of convenience, because if they return the data it'd be possible to "compose" them in one liners, like for example in the fixture definitions (as before). Anyway, it's a minor issue and this PR is already good to go, so you don't need to change it if you don't think it is useful. If no one else has any comments on this, I will finally merge the PR tomorrow.

**Pull request merged**
