### PR TITLE
refactor: use modern-style type hints

### PR DESCRIPTION
**Pull request by romanc**
## Description

In the past, the only way to create type hints for yet-to-be-defined types was to quote them. Since python 3.7 we can get rid of the quotes when using `annotations` from `__future__` instead. This is supposed to become the default in the future.

This PR is a spin-off from https://github.com/GridTools/gt4py/pull/1630#issuecomment-2333757200. 

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

### CODE REVIEW

**Comment by romanc** [comment]
/cc @egparedes 

@FlorianDeconinck FYI as mentioned earlier

**Comment by FlorianDeconinck** [comment]
The Great Cleanup continues. All we be cleansed!

**Comment by egparedes** [comment]
cscs-ci run

**Review by egparedes — APPROVED** [review]
LGTM

**Comment by romanc** [comment]
Thanks for running cscs-ci and approving. Please merge whenever is convenient for you (since I don't have write access to this repo) or let me know if you want me to rebase the PR on top of latest changes in `main`.

**Pull request merged**
