### PR TITLE
CI: Enable pip caching

### PR DESCRIPTION
**Pull request by havogt**
see https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/

### CODE REVIEW

**Comment by havogt** [comment]
re-evaluate once https://github.com/actions/setup-python/pull/303 is merged

**Comment by gronerl** [comment]
Said PR was merged.

**Comment by havogt** [comment]
I don't remember why I added this. Does it make sense to merge it? @egparedes @gronerl

**Comment by havogt** [comment]
implemented in #1163

**Pull request closed without merging**
