### PR TITLE
Use make_module_from_file in gtc:numpy

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Use a load-retry loop with importlib instead of editing `sys.path` in the `gtc:numpy` backend.

Resolves https://github.com/GridTools/gt4py/issues/714.

### CODE REVIEW

**Review by egparedes — APPROVED** [review]
It looks good.

**Comment by egparedes** [comment]
bors try

**Comment by gronerl** [comment]
Huh I just arrived at the same solution :D Can someone explain what is different in this case, and why it seems to solve #540 and #714 ?

**Comment by gronerl** [comment]
This fix also works on a branch that does not have support for `GT_CACHE_LOAD_RETRY_DELAY`, and reading the m_computation file directly after writing in my reliable reproducer hints that it can immediately be read without problems and that a delay wouldn't help. Do we fully understand the issue?

**Comment by jdahm** [comment]
Not fully, but the code that was there originally was quite poor :)

Here is one concern of mine with the original code:
```
                "path_backup = sys.path.copy()",
                "sys.path.append(str(pathlib.Path(__file__).parent))",
                f"import {comp_pkg} as computation",
                "sys.path = path_backup",
                "del path_backup",
```
What happens (I think, haven't checked) is that `sys.path = path_backup` is not actually doing a deep copy, so the `del path_backup` sets the path in an odd state. Even if that's fine, this is not thread safe.

**Comment by egparedes** [comment]
> Not fully, but the code that was there originally was quite poor :)
> 
I agree, the original code was very error-prone (to say the least) and the code in this PR is simply better.

**Pull request merged**
