### PR TITLE
Fix argument order in classic GT backend bindings

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR modifies the GT backends (in the original toolchain) to emit arguments in API signature order to the C++ bindings (`bindings.cpp`). This fix resolves the error described in issue #365.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

### CODE REVIEW

**Review by egparedes — CHANGES_REQUESTED** [review]
I think it would be cleaner to reorder the group of fields and the group of parameters  in the python side following the API order before passing them to the template. I sketched the solution in my `fix_365` branch but didn't have time to test it properly. You can use it here:
https://github.com/egparedes/gt4py/commit/29519af95d0434adb4f24a8bdcc229200db103ec

Additionally, it would be good to add a simple test case to be able to reproduce and fix the current error.

**Comment by eddie-c-davis** [comment]
Thank you @egparedes, your excellent feedback has been implemented and tested.

**Comment by egparedes** [comment]
bors try

**Comment by jdahm** [comment]
Resolves #365.

**Review by havogt — CHANGES_REQUESTED** [review]
This breaks the GTC backends. I'd like to discuss with @egparedes what's the best (most future-proof) way to resolve this.

If you have time @eddie-c-davis, you could already add a test, with the example code from the issue. It should fail for GTC.

**Comment by havogt** [comment]
Hi Eddie, very sorry, we think your initial fix is actually the proper one, i.e. parameter order in bindings should match the order in the stencil signature (as is currently implemented in the GTC backends). I'll roll back your latest changes. Hope that's fine.

**Comment by havogt** [comment]
bors try

**Comment by havogt** [comment]
bors try

**Comment by eddie-c-davis** [comment]
Thank you both for getting this merged!

**Pull request merged**
