### PR TITLE
refactor[cartesian]: Warn if GT4Py can't find DaCe

### PR DESCRIPTION
**Pull request by romanc**
## Description

DaCe backends are optional backends in the cartesian version of GT4Py. Currently, we silently drop support for DaCe backends if DaCe can't be imported. This can can happen because DaCe isn't available or for a couple other reasons (e.g. a circular import in the import path). With this PR we thus add a warning message allowing developers to easily figure out that/why DaCe backends are disabled.

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

### CODE REVIEW

**Comment by romanc** [comment]
@egparedes would you have time for a review?

/cc @FlorianDeconinck  as discussed

**Review by egparedes — APPROVED** [review]
Thanks for the PR. It looks much better now.

**Comment by romanc** [comment]
> Thanks for the PR. It looks much better now.

Thanks for the quick review. Could you also kick-off the CSCS CI job? Thanks! :pray:

**Comment by egparedes** [comment]
cscs-ci run

**Comment by romanc** [comment]
Thanks for running CSCS CI, Enrique.

Regarding the branch update: the branch is already outdated again. You might find [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) an interesting option to avoid such situations. Merge queues provide the same level of security as requiring an up-to-date branch without authors (or maintainers) having to update branches manually.

**Comment by egparedes** [comment]
> Regarding the branch update: the branch is already outdated again. You might find [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) an interesting option to avoid such situations. Merge queues provide the same level of security as requiring an up-to-date branch without authors (or maintainers) having to update branches manually.

Thanks for the suggestion. We briefly considered to use merge queues in the past but given that the number of PRs merged per day is not really high, it's probably not worth it.

**Pull request merged**
