### PR TITLE
Backend support for horizontal masks

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Follow-on to #678. Adds backend support for horizontal masks.

Backends:
- [x] gtcpp
- [x] cuda
- [x] numpy
- [x] dace -- Thanks @gronerl!

### CODE REVIEW

**Comment by gronerl** [comment]
bors try

**Review by gronerl — APPROVED** [review]

**Comment by gronerl** [comment]
GPU CI failing on `gtc:cuda` backend, with errors like: 
```
----------------------------- Captured stderr call -----------------------------
/scratch/snx3000/jenkssl/gitlab-runner/builds/tT2LGsd8/0/cscs-ci-gridtools-gt4py/cscs-ci/gridtools/gt4py/.tox/py38-all-cuda101/lib/python3.8/site-packages/gt4py/_external_src/gridtools2/include/gridtools/stencil/gpu/launch_kernel.hpp(145): error: static assertion failed with "GridTools encountered an internal error. Please submit the error message produced by the compiler to the GridTools Development Team."
          detected during instantiation of "void gridtools::stencil::gpu_backend::launch_kernel_impl_::launch_kernel<Extent,BlockSizeI,BlockSizeJ,Fun,<unnamed>>(gridtools::int_t, gridtools::int_t, gridtools::uint_t, Fun, size_t) [with Extent=gridtools::stencil::extent<0, 0, 0, 1, 0, 0>, BlockSizeI=64, BlockSizeJ=8, Fun=native_functions_impl_::kernel_140735918158512_f<native_functions_impl_::loop_140735908777120_f<gridtools::sid::composite::keys<native_functions_impl_::tag::field_b, native_functions_impl_::tag::field_a>::values<gridtools::sid::block_impl_::blocked_sid<gridtools::sid::shift_sid_origin_impl_::shifted_sid_type<gridtools::sid::shift_sid_origin_impl_::shifted_sid_type<gridtools::sid::synthetic_impl_::synthetic<gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::upper_bounds, gridtools::array<size_t, 3UL>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::lower_bounds, gridtools::array<gridtools::integral_constant<size_t, 0UL>, 3UL>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::strides_kind, gridtools::python_sid_adapter_impl_::kind<3UL, gridtools::integral_constant<int, 2>>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::strides, gridtools::tuple<gridtools::integral_constant<pybind11::ssize_t, 1L>, size_t, size_t>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::origin, gridtools::sid::host_device::simple_ptr_holder<double *>>>, std::array<gridtools::int_t, 3UL> &> &, gridtools::hymap::keys<gridtools::stencil::dim::k>::values<int> &>, gridtools::hymap::keys<gridtools::stencil::dim::i, gridtools::stencil::dim::j>::values<native_functions_impl_::i_block_size_t, native_functions_impl_::j_block_size_t>>, gridtools::sid::block_impl_::blocked_sid<gridtools::sid::shift_sid_origin_impl_::shifted_sid_type<gridtools::sid::shift_sid_origin_impl_::shifted_sid_type<gridtools::sid::synthetic_impl_::synthetic<gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::upper_bounds, gridtools::array<size_t, 3UL>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::lower_bounds, gridtools::array<gridtools::integral_constant<size_t, 0UL>, 3UL>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::strides_kind, gridtools::python_sid_adapter_impl_::kind<3UL, gridtools::integral_constant<int, 1>>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::strides, gridtools::tuple<gridtools::integral_constant<pybind11::ssize_t, 1L>, size_t, size_t>>, gridtools::sid::synthetic_impl_::unique_mixin<gridtools::sid::property::origin, gridtools::sid::host_device::simple_ptr_holder<double *>>>, std::array<gridtools::int_t, 3UL> &> &, gridtools::hymap::keys<gridtools::stencil::dim::k>::values<int> &>, gridtools::hymap::keys<gridtools::stencil::dim::i, gridtools::stencil::dim::j>::values<native_functions_impl_::i_block_size_t, native_functions_impl_::j_block_size_t>>>>>, <unnamed>=0]" 
.gt_cache_pytest_kv55b0fn/py38_1013/gtccuda/tests/test_integration/test_code_generation/native_functions/m_native_functions__gtccuda_207c974eb8_pyext_BUILD/computation.hpp(196): here
```
Ever seen those?

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try-
bors try

**Pull request merged**
