### PR TITLE
Improve error when calling fcns in args to fcns

### PR DESCRIPTION
**Pull request by jdahm**
## Description

This used to have a cryptic error message.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [x] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [x] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by egparedes** [comment]
It feels like it would be better to support the nested function calls in the function arguments (only when the function returns a single argument). Have you considered it? Do you have a rough estimate of how much effort would imply?

**Comment by jdahm** [comment]
> It feels like it would be better to support the nested function calls in the function arguments (only when the function returns a single argument). Have you considered it?

Yes, I'd like to support this. I thought in the meantime it's nice to have an understandable error.

**Comment by egparedes** [comment]
> Yes, I'd like to support this. I thought in the meantime it's nice to have an understandable error.

Good point. I'll approve the PR and wait for another PR supporting the feature.

**Review by egparedes — APPROVED** [review]
It looks good.

**Pull request merged**
