### PR TITLE
[Minor] Slightly improve frontend error messages

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Minor improvements to frontend `GTScriptSyntaxError` messages.

### CODE REVIEW

**Comment by jdahm** [comment]
I would like to get the actual source file and line using `inspect` instead of `<source> line X...`, but we're not passing around the function object, and from a quick look that seemed to be more involved throughout `gtscript_frontend.py` that might not be worth it until rewriting the frontend. Thoughts @egparedes?

**Comment by gronerl** [comment]
I think those `loc` are only for exactly this purpose, so it is surely fine to just offset those. This is a hacky way of achieving this, but there are probably nicer ways out there. (Like, make a visitor to modify the ast maybe.)
```
diff --git a/src/gt4py/frontend/gtscript_frontend.py b/src/gt4py/frontend/gtscript_frontend.py
index 31fc4fd3..01d9e438 100644
--- a/src/gt4py/frontend/gtscript_frontend.py
+++ b/src/gt4py/frontend/gtscript_frontend.py
@@ -1280,7 +1280,7 @@ class GTScriptParser(ast.NodeVisitor):
         self.definition = definition
         self.filename = inspect.getfile(definition)
         self.source, decorators_source = gt_meta.split_def_decorators(self.definition)
-        self.ast_root = ast.parse(self.source)
+        self.ast_root = ast.parse(("\n") * inspect.getsourcelines(definition)[1] + self.source)
         self.options = options
         self.build_info = options.build_info
         self.main_name = options.qualified_name
```

**Comment by egparedes** [comment]
@jdahm Any news about this PR? Is it still being actively developed or should it be closed?

**Comment by jdahm** [comment]
I think realistically improving the frontend error messages would entail a much larger reorganization of the code, so I'll close this for now.

**Pull request closed without merging**
