### PR TITLE
feature[cartesian]: Add log10: as a native function

### PR DESCRIPTION
**Pull request by oelbert**
Feature[cartesian]: Add log10: as a native function

## Description

Adds the ability to evaluate base-10 logarithms inside stencils.

## Requirements

- [x] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] All the authors are covered by a valid contributor assignment agreement provided to ETH Zurich and signed by the employer if needed.
- [x] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

### CODE REVIEW

**Comment by oelbert** [comment]
> This looks right to me, but I can't tell unless there are some tests for it. What do you think the right approach for that is? The easiest would be to add it [here](https://github.com/GridTools/gt4py/blob/main/tests/cartesian_tests/integration_tests/multi_feature_tests/stencil_definitions.py#L113) but it might be useful to incorporate unit tests also?

I did add log10 to the native functions test, but a separate unit test wouldn't be the worst idea. I'm just not sure how to go about writing that for gt4py?

**Comment by jdahm** [comment]
> I did add log10 to the native functions test

Apologies, I missed that!

> but a separate unit test wouldn't be the worst idea. I'm just not sure how to go about writing that for gt4py?

I took a closer look at the existing unit tests. There are already [some tests](https://github.com/search?q=repo%3AGridTools%2Fgt4py+native+function+path%3A%2F%5Etests%5C%2Fcartesian_tests%5C%2F%2F&type=code) for that, so not needed!

**Review by jdahm — APPROVED** [review]

**Comment by jdahm** [comment]
Can you rename the PR before merging to follow the naming convention that seems to have been adopted since the merge of next with cartesian? Otherwise this looks ready to go from my end.

**Comment by oelbert** [comment]
Done, thanks!

**Comment by havogt** [comment]
cscsci run

**Comment by havogt** [comment]
cscs-ci run

**Review by havogt — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
