### PR TITLE
fix[cartesian]: Fix serialize default behavior when Pickled property was not saved

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
## Description

DaCe has a behavior of _not_ saving properties if they have a default (newish behavior) which leads our 2-step process of library node caching to fail. Since we have decided to rely on pickling to cache out the content of the LibraryNode we respond to this change in DaCe by making sure default values pass to the pickle deserializer are returned plain

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

### CODE REVIEW

**Comment by FlorianDeconinck** [comment]
Poke @romanc

**Comment by edopao** [comment]
It seems related to the change I made to the test code [tests/cartesian_tests/integration_tests/multi_feature_tests/test_dace_parsing.py](https://github.com/GridTools/gt4py/pull/1556/files#diff-f6a56a555a5c57b6ff6df2e50805789eda99d1e15b1d3f2f060efb4df3f3ecbb) when I upgraded the DaCe package version. Is it possible that with your fix we can undo my change?

**Review by romanc — COMMENTED** [review]
Looks good to me. Looking forward to not having to nuke my cache anymore all the time :partying_face:

**Comment by FlorianDeconinck** [comment]
> It seems related to the change I made to the test code [tests/cartesian_tests/integration_tests/multi_feature_tests/test_dace_parsing.py](https://github.com/GridTools/gt4py/pull/1556/files#diff-f6a56a555a5c57b6ff6df2e50805789eda99d1e15b1d3f2f060efb4df3f3ecbb) when I upgraded the DaCe package version. Is it possible that with your fix we can undo my change?

Should be, pushing code now

**Review by twicki — APPROVED** [review]
Looks good to me!

**Review by twicki — APPROVED** [review]

**Review by edopao — APPROVED** [review]
Thanks @FlorianDeconinck for addressing my comment. LGTM

**Pull request merged**
