### PR TITLE
Sort temporary fields in GT backends

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR sorts the temporary fields in the GT backends by name to ensure that the same code is generated each time a stencil is compiled for reproducibility.

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

### CODE REVIEW

**Review by egparedes — APPROVED** [review]
It looks good. I'll merge as soon the CI tests finish.

**Comment by eddie-c-davis** [comment]
Thank you very much, @egparedes!

**Comment by egparedes** [comment]
This was previously a single line commit and now there are 18 files modified. If you have time, could you try to merge/rebase on the current master again or open a new PR with the single line fix starting from master?

**Comment by eddie-c-davis** [comment]
My apologies, I was attempting to resolve the formatting issues and made the issue worse. I will create a new PR.

**Pull request closed without merging**
