### PR TITLE
Remove legacy backends

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Removes legacy backends and test files. Part of #566.

Blocked by #673.

### CODE REVIEW

**Comment by jdahm** [comment]
No, but I haven't tested this branch with GPUs on Daint yet. I'll do that today.

**Comment by egparedes** [comment]
bors try

**Review by egparedes — APPROVED** [review]
It looks good to me, but just a question: are the files in `backend/templates` still needed or could they be also removed in this PR?

**Comment by jdahm** [comment]
I think `stencil_module.py.in` is still used, but the others I believe can be deleted. Good catch. I'll try that today.

**Comment by jdahm** [comment]
@egparedes Can you re-review? I:

- Moved `location_to_source_location`
- Removed `USE_LEGACY_BACKEND`
- Removes `gt4py.ir` and moves source into `gt4py.frontend`

**Review by egparedes — COMMENTED** [review]
Thanks for the extra changes. I suggest the following changes:

- rename the new `utils` in `frontend` to `node_utils` or something like that, which I think is more representative of the contents of the module
- delete `computation.src.in` from `backend/templates` which I think it's not used at all
- Update `frontend.nodes` with more suitable docstrings and remove Implementation IR nodes, which are not longer used.

**Comment by jdahm** [comment]
bors try

**Pull request merged**
