### PR TITLE
Fix for #241

### PR DESCRIPTION
**Pull request by tehrengruber**
## Description

See #241

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [x] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [x] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by egparedes** [comment]
What is the current state of this PR? Is it still in progress or is it already ready for review?

**Comment by tehrengruber** [comment]
@gronerl This is ready for review

**Comment by gronerl** [comment]
Actually, are #241 and #246 duplicates?

**Review by gronerl — APPROVED** [review]

**Comment by fthaler** [comment]
> Actually, are #241 and #246 duplicates?

I would assume they are not as #241 affects all backends while #246 is failing only with GT backends. But then I don’t know the internals…

**Pull request merged**
