### PR TITLE
refactor[catesian]: Type hints and code redability improvements

### PR DESCRIPTION
**Pull request by romanc**
## Description

This PR is split off the work for the new GT4Py - DaCe bridge, which should allow to expose control flow statements (`if` and `while`) to DaCe to better use DaCe's analytics capabilities. This PR is concerned with adding type hints and generally improving code readability. Main parts are

- `daceir_builder.py`: early returns and renamed variable
- `sdfg_builder.py`: type hints and early returns
- `tasklet_codegen.py`: type hints and early returns

`TaskletCodegen` was given `sdfg_ctx`, which wasn't used. That parameter was thus removed.

Parent issue: https://github.com/GEOS-ESM/NDSL/issues/53

## Requirements

- [x] All fixes and/or new features come with corresponding tests.
  Assumed to be covered by existing tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.
  N/A

### CODE REVIEW

**Comment by romanc** [comment]
@twicki, @FlorianDeconinck: The great cleanup continues. Pulling out as much as I can from https://github.com/GridTools/gt4py/compare/main...romanc:romanc/dace-bridge-no-sdfgs before switching tasks.

@egparedes would you mind kicking off CSCS CI for us?

**Review by FlorianDeconinck — APPROVED** [review]
LGTM

**Comment by havogt** [comment]
Are yo aware of the mypy excludes here https://github.com/GridTools/gt4py/blob/6873a0e7f87e43ed717cc22611793a81afce0c93/pyproject.toml#L170 ? You could play with these settings to enable stricter mypy settings in the files that you fixed.

**Review by twicki — APPROVED** [review]
Looks good.

**Comment by romanc** [comment]
> Are yo aware of the mypy excludes here
> 
> https://github.com/GridTools/gt4py/blob/6873a0e7f87e43ed717cc22611793a81afce0c93/pyproject.toml#L170
> ? You could play with these settings to enable stricter mypy settings in the files that you fixed.

Thanks for the pointer @havogt, I wasn't aware. I'll see what we can do there in a follow-up PR if that is okay with you.

Meanwhile, I updated the branch with latest `main`. If someone from CSCS would kick off the CSCS-CI for me, I'd be grateful :pray:

**Comment by tehrengruber** [comment]
cscs-ci run

**Pull request merged**
