### PR TITLE
Naive OIR Iteration Space

### PR DESCRIPTION
**Pull request by gronerl**
## Description

Adds iteration space to OIR horizontal executions, by computing them in the style of the old backends. 
## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

### CODE REVIEW

**Comment by gronerl** [comment]
I will add some unit testing, but please let me know if you think the representation makes sense.

**Comment by egparedes** [comment]
@gronerl @havogt @fthaler Is this PR still relevant? Should it be updated and merged?

**Comment by gronerl** [comment]
Not in this version and without further discussion. The concept didn't gain any traction, so for the DaCe backend, I extracted it again from OIR and instead compute the same information with an utility as needed, instead of making it part of OIR. However, I still think such a concept should be part of OIR in principle. I guess we could mark the PR closed, and maybe open an issue instead as a reminder.

**Comment by havogt** [comment]
I'll close. You won't forget that this thing exists and can bring it up if it becomes relevant.

**Pull request closed without merging**
