### PR TITLE
refactor[cartesian]: readability improvements in gtir -> oir conversion and other cleanups

### PR DESCRIPTION
**Pull request by romanc**
## Description

Being new to the codebase and in preparation of the [GT4Py-DaCe bridge refactor](https://github.com/GEOS-ESM/NDSL/issues/53) I was reading a lot of code. Some things that caught my eye are summarized in this PR. Bigger changes include

1. Moving `daceir.py` into the `dace/` backend folder. This follows the convention of all other backends who have their IR inside the backend folder. (last commit)
2. Readability improvements in `gtir_to_oir.py` (the "Cleanup visit_*" commits): In my opinion, there's no point in shortening "statement" to "stmt". I wouldn't go as far as renaming the classes. For the renamed local variables, I think this adds a lot to readability.
3. `visit_While` in `gtir_to_oir.py` was having an extra mask statement around the `while`  loop (in case a mask was defined. I inlined the potential `mask`  with the condition of `while`  loop.
4. In `gtir_to_oir.py` don't translate every body statement into a single `MaskStmt`. Instead, create one (or two incase of `else`) `MaskStmt`  with multiple statements in the `body` (which is already typed as a list of statements).

Tested locally by running the test suite. All tests passing.

## Requirements

- [ ] All fixes and/or new features come with corresponding tests.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.

If this PR contains code authored by new contributors please make sure:

- [ ] The PR contains an updated version of the `AUTHORS.md` file adding the names of all the new contributors.

### CODE REVIEW

**Comment by romanc** [comment]
@egparedes is it okay to do such arguably stylistic/cosmetic changes?

/cc @twicki @FlorianDeconinck

**Comment by romanc** [comment]
Fixed the newly added type hints. Apparently `TypeX | TypeY`  is only supported starting with python 3.10. Using `Union[TypeX, TypeY]` (like in the rest of the codebase) instead.

**Review by FlorianDeconinck — APPROVED** [review]
LGTM

**Comment by egparedes** [comment]
> @egparedes is it okay to do such arguably stylistic/cosmetic changes?

Sure, if the changes make the code better and don't break the coding conventions I don't see why not.
By the way, there is no point in using explicit strings as type annotations when the module is using lazy annotation evaluations ( `from __future__ import annotations`). I know the unneeded _stringification_ of  the annotations was already there in many functions and modules and it's outside the scope of this PR to change it, but just to let you know...

I you update the PR to the current `main`, I can merge it afterwards.

**Comment by romanc** [comment]
> By the way, there is no point in using explicit strings as type annotations when the module is using lazy annotation evaluations ( `from __future__ import annotations`). I know the unneeded _stringification_ of the annotations was already there in many functions and modules and it's outside the scope of this PR to change it, so it's just to let you know...

Oh nice. My python is a bit outdated so I just copy-pasted. Now that I've read up on it, I agree, we should just use the new-style annotations. I'll create a separate PR as suggested.

> I you update the PR to the current `main`, I can merge it afterwards.

Let's wait and see if @twicki has anything to say about this PR today. If there's no response by Monday, we can safely merge next week.

**Comment by egparedes** [comment]
cscs-ci run

**Comment by romanc** [comment]
> > By the way, there is no point in using explicit strings as type annotations when the module is using lazy annotation evaluations ( `from __future__ import annotations`). I know the unneeded _stringification_ of the annotations was already there in many functions and modules and it's outside the scope of this PR to change it, so it's just to let you know...
> 
> Oh nice. My python is a bit outdated so I just copy-pasted. Now that I've read up on it, I agree, we should just use the new-style annotations. I'll create a separate PR as suggested.

I've done this work in PR https://github.com/GridTools/gt4py/pull/1632. Let's merge PR https://github.com/GridTools/gt4py/pull/1632 first (I'll deal with any potential conflicts) because then it will be simpler to see which new "stringized" types I have introduced with this PR.

**Comment by egparedes** [comment]
> @egparedes can you help me understand what the CI results from cscs mean? As far as I understand
I don't really understand it. Let's sync again this branch with `main` and try again.

**Comment by romanc** [comment]
> > @egparedes can you help me understand what the CI results from cscs mean? As far as I understand

> I don't really understand it. Let's sync again this branch with `main` and try again.

sure, let's try and see - I'll rebase tomorrow once PR #1632 (new style type hints) is merged. That will anyway trigger updates in this branch too

**Comment by romanc** [comment]
okay so I rebased onto `main`  and included changes from PR https://github.com/GridTools/gt4py/pull/1632 and now I get a CI error with jupyter notebooks. The jupyter notebook tests are fine on PR #1632 (and I guess on `main`  too) and were fine before. The only new thing is commit d8dd0f9 fixing one more annotation. I guess that shouldn't break tests, right? Getting a bit confused here ...

**Comment by egparedes** [comment]
Let's solve the merge conflicts again first, and then I'll try to take a look if this PR still fails to pass the tests

**Comment by romanc** [comment]
> Let's solve the merge conflicts again first, and then I'll try to take a look if this PR still fails to pass the tests

CI seems to be more happy today :tada:

**Pull request merged**
