### PR TITLE
Fix backend names in examples

### LINKED ISSUE #799: simple example problem
I am attempting to run the simple example from the quick start guide,  I see the numpy backend, why isn't it working?

 python simpex.py 
Traceback (most recent call last):
  File "simpex.py", line 8, in <module>
    def stencil_example(
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/gtscript.py", line 276, in _decorator
    out = gt_loader.gtscript_loader(
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/loader.py", line 72, in gtscript_loader
    stencil_class = load_stencil("gtscript", backend, definition_func, externals, build_options)
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/loader.py", line 48, in load_stencil
    raise ValueError("Unknown backend name ({name})".format(name=backend_name))
ValueError: Unknown backend name (numpy)

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Fixes a few backend names in ipython notebooks and the quickstart. Resolves #799.

### CODE REVIEW

**Review by tehrengruber — APPROVED** [review]

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
It does not give me confidence that I launched the CI tests 3 times each with a different and odd failure.

1. Problem described in #812 with building the image
2. Some sort of file not found error
3. DaCe failures that should have been fixed by https://github.com/GridTools/gt4py/commit/2a7294d6d48b63a28fc38cffac160bd9c0e9847f but might have not been. cc: @gronerl?

**Comment by DropD** [comment]
bors try

**Pull request merged**
