### PR TITLE
Add workaround for DaCe StringLiteral issue

### PR DESCRIPTION
**Pull request by jdahm**
Work around https://github.com/spcl/dace/issues/1100.

### CODE REVIEW

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
Looks like something is wrong with the CI system on Daint.

**Comment by jdahm** [comment]
@havogt this should work the same with the GPU backend (changes are independent of the backend). Could you force merge if needed? Would like to get `master` passing CI again ASAP.

**Comment by havogt** [comment]
bors try

**Review by havogt — APPROVED** [review]

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
bors try

**Comment by jdahm** [comment]
Looks like it passed, but failed to pass the success state back to GitHub. @egparedes can you override and merge it?

**Comment by egparedes** [comment]
Done

**Pull request merged**
