### PR TITLE
GDP-3: Duck Storages: reference implementation

### PR DESCRIPTION
**Pull request by gronerl**
## Description
This is the implementation of `GDP-3: Duck Storages` (in progress)

GDP-3 PR: https://github.com/GridTools/gt4py/pull/28

In its current state, this branch is not yet a full implementation of the GDP-3, yet most of the main changes that impact how you use the storages are supposed to be there. Noteable gaps are:

* Construction from templates which implement the `__array_interface__`, `__cuda_array_interface__` and `__gt_data_interface__` only is faulty.
* Storages are still assumed to be in IJK order when passed to stencils, since the generated code is not yet able to flexibly handle nonstandard layouts and this functionality would be very limited.
* As a consequence of the last point, the xarray `__gt_data_interface__` property has not been implemented yet, since without the "dims", this functionality would be very restrictive on how the DataArray can be used. 
* The raising of errors for incompatible or inconsistent parameters is in largely untested. Given valid parameters, this should be working, though.

### CODE REVIEW

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Comment by havogt** [comment]
obsolete, will be replaced by a simpler approach.

**Pull request closed without merging**
