### PR TITLE
npir_codegen.py: Add rhs check to visit_FieldSlice when generating np.broadcast_to calls

### LINKED ISSUE #598: Value error for IJ fields related ot np.broadcast in gtc:numpy
The following program validates with `gtc:gt:cpu_ifirst`, but fails with `gtc:numpy`:

```python
import numpy as np
from gt4py.gtscript import FORWARD, computation, interval, stencil, Field, IJK, IJ
from gt4py.storage import ones

BACKEND = "gtc:numpy"  # "gtc:gt:cpu_ifirst" yields correct results
dtype = np.float64


@stencil(BACKEND)
def numpy_bug(fld3D: Field[IJK, dtype], fld2D: Field[IJ, dtype]):

    with computation(FORWARD), interval(0, -1):
        fld2D += fld2D
        if fld2D >= 10.0:
            fld2D = 0.0
        fld3D = fld2D

    with computation(FORWARD), interval(-1, None):
        fld2D += fld2D
        if fld2D >= 10.0:
            fld2D = 0.0
        fld3D = fld2D

if __name__ == "__main__":

    origin = (0, 0, 0)
    fld3D = ones(shape=(2, 3, 4), dtype=dtype, backend=BACKEND, default_origin=origin)
    fld2D = ones(shape=(2, 3), dtype=dtype, backend=BACKEND, default_origin=origin)

    numpy_bug(fld3D, fld2D)
    print(fld3D)
```
The `fld3D` is not strictly necessary to reproduce the error.

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Resolves #598.

### CODE REVIEW

**Comment by jdahm** [comment]
@havogt I cannot reproduce the test error here. This comes from the `_validate_lvalue_dims` validator on `gtir.Stencil`, but the `StencilFactory` should have already added the symbols to the table. On my machine it passes. Any chance you could test that?

**Comment by jdahm** [comment]
@leuty This PR should fix the issue. Thanks for reporting it!

**Review by DropD — COMMENTED** [review]
Thanks! looks like it should fix it. Any chance you could add a test so it stays fixed? Or help me write one?

**Comment by DropD** [comment]
I added a regression test. @jdahm Do you think it catches what it should?

**Comment by DropD** [comment]
bors try

**Comment by DropD** [comment]
bors try

**Comment by DropD** [comment]
bors retry

**Comment by DropD** [comment]
bors try-

**Comment by DropD** [comment]
bors try

**Pull request merged**
