### PR TITLE
New precommit hooks

### PR DESCRIPTION
**Pull request by egparedes**
## Description

Update pre-commit versions and configs (in two commits to simplify merging other branches).

Main changes:
- update hooks versions
- remove encoding pragma (disabled)
- add license headers (disabled)
- autoformat ini files
- autoformat yaml files
- extra check for merge conflicts
- extra check for debug statements
- extra check for unnecesary #noqa pragmas (applied once but disabled)

### CODE REVIEW

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
bors try

**Comment by DropD** [comment]
bors try

**Comment by DropD** [comment]
> ## try
> Build failed:
> 
> * [ci/gitlab/full-pipeline](https://gitlab.com/cscs-ci/gridtools/gt4py/-/pipelines/257402266)

It looks like this was due to a temporary unavailability of the jfrog docker registry.

**Review by DropD — APPROVED** [review]
👍

**Pull request merged**
