### PR TITLE
ci: use actions/checkout@v4 and actions/setup-python@v5

### PR DESCRIPTION
**Pull request by romanc**
## Description

This PR updates the GitHub Actions (GHA) workflows to use `actions/checkout@v4` instead of `v3` (or `v2`  in the cartesian case) and `actions/setup-python@v5`. Development for `actions/checkout@v3` and `actions/setup-python@v4` stopped ~1 year ago and GH is currently enforcing newer node versions than the one that these actions were designed with, leading to the following warnings

image
_warnings in next workflows_

image
_warnings in cartesian workflows_

`deploy_release` action was following `actions/checkout@master`. Was this on purpose? Happy to revert if so. Unless there's a good reason, I suggest to keep all actions pinned at ideally the same major version.

`pre-commit/action` was updated to keep its dependencies up to date and avoid transitive warnings similar to the ones above.

No changes made to currently disabled workflows, i.e. the ones under `.github/workflows/_disabled/`.

Parent: https://github.com/GEOS-ESM/SMT-Nebulae/issues/89

## Requirements

- [x] All fixes and/or new features come with corresponding tests.
  CI is running as before - just with fewer warnings.
- [ ] Important design decisions have been documented in the approriate ADR inside the [docs/development/ADRs/](docs/development/ADRs/Index.md) folder.
  N/A

### CODE REVIEW

**Comment by romanc** [comment]
@twicki / @FlorianDeconinck continuing the quest to reduce warnings ...

@egparedes / @havogt please review or re-distribute to whoever is knowledgeable / in charge of CI for the next version of gt4py

As far as I can tell, we should be good again for now. We might want to look into automatic reporting of outdated GHA versions in the future.

**Comment by romanc** [comment]
We should also be aware the `pre-commit/action` is in [maintenance mode only](https://github.com/pre-commit/action) (see top of their README file). I wouldn't be very concerned. If we are happy with what we have now, it's super straight forward to just implement ourselves (instead of using their composite action) in case it ever drops support completely.

**Comment by egparedes** [comment]
cscs-ci run

**Review by egparedes — APPROVED** [review]
LGTM

**Review by havogt — APPROVED** [review]

**Pull request merged**
