### PR TITLE
Fix HorizontalExecution merging transformations

### PR DESCRIPTION
**Pull request by gronerl**
* prevent OTF to merge if intermediate is used later or is signature parameter
* prevent GraphMerging if iteration spaces don't match and any output is API
* remove GreedyMerging, since not used anywhere and above issue can't be fixed there easily
* also applies OTF repeatedly, which can increase the number of valid matches.

### CODE REVIEW

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Review by DropD — APPROVED** [review]
👍

**Comment by gronerl** [comment]
bors try

**Pull request merged**
