### PR TITLE
Higher-dimensional Fields for gtc:cuda Backend

### PR DESCRIPTION
**Pull request by fthaler**
## Description

Introduces support for higher-dimensional fields in the gtc:cuda backend.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [x] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [x] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by fthaler** [comment]
bors try

**Comment by fthaler** [comment]
bors try

**Review by egparedes — APPROVED** [review]
It looks good, way simpler than expected (except for the C++ code with the `multi_shifted` and `hymap` stuff that probably does all the magic :smile: )

**Comment by fthaler** [comment]
bors try

**Pull request merged**
