### PR TITLE
Fix explicit assignment to zero offset in python 3.9

### PR DESCRIPTION
**Pull request by tehrengruber**
## Description

Python 3.9 doesn't use the deprecated `ast.Index` node anymore leading to errors when using assignments like

```python
field[0, 0, 0] = 1
```

## Requirements

Before submitting this PR, please make sure:

- [ ] The code builds cleanly without new errors or warnings
- [ ] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [x] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by gronerl** [comment]
bors try

**Review by gronerl — APPROVED** [review]

**Comment by tehrengruber** [comment]
Blocked by unstructured tests failing on 3.9. Will be fixed as soon as `icon_hackathon_cleanup` is merged.

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
tests can be made to pass with 
```
diff --git a/tests/eve_tests/unit_tests/test_iterators.py b/tests/eve_tests/unit_tests/test_iterators.py
index 54e58f97..599b987e 100644
--- a/tests/eve_tests/unit_tests/test_iterators.py
+++ b/tests/eve_tests/unit_tests/test_iterators.py
@@ -30,6 +30,7 @@ class Tree(eve.Node):
 
 def _make_tree(values_list):
     children = [_make_tree(item) if isinstance(item, list) else item for item in values_list]
+    Tree.update_forward_refs()
     return Tree(children=children)
 

```
that doesn't seem like neither a nice solution nor a py39 issue though. @egparedes  do you understand what's going on?

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Pull request merged**
