### PR TITLE
Add 'device_sync' backend option

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR adds a backend option called `device_sync` to the GPU backends. If the option is set to `False`, the `cupy` synchronization method will not be generated at the end of each stencil call. This allows a calling application to schedule its own GPU synchronization independently.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

### CODE REVIEW

**Comment by havogt** [comment]
We should do this for all backends.

**Comment by havogt** [comment]
I pushed a change to the test, should work for the gtc backend without change as it is using the same base.

**Review by havogt — APPROVED** [review]
Looks good. There is currently a refactoring pending which touches these files, will merge afterwards.

**Comment by eddie-c-davis** [comment]
Thank you very much @havogt .

**Comment by gronerl** [comment]
The other refactoring blocking this was done, I have resolved the conflicts, but can't push to this branch. Please accept eddie-c-davis/gt4py#6

**Comment by eddie-c-davis** [comment]
PR #6 has been merged.

**Pull request merged**
