### PR TITLE
Forward Iteration Order Fix

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR resolves an issue that occurs when the iteration order of a stencil is changed from `PARALLEL` to `FORWARD. The example in the provided integration test highlights the problem.

```python
@function
def smul_add(in_f, factor=2.0):
    return factor * (in_f + in_f[1, 0, 0])

@stencil
def double_smul_parallel(in_f: Field[float], out_f: Field[float]):  # type: ignore
    with computation(PARALLEL), interval(...):  # type: ignore
        tmp_f = smul_add(in_f)
        out_f = smul_add(tmp_f)
```

The `factor` parameter is converted into two temporary fields, one per stage. In the `PARALLEL` case, the two temporary fields are demoted to scalar variables by the `DemoteLocalTemporariesToVariablesPass` and the generated code is correct.
```
stage_1:
    factor_tmp_1 = 2.0
    tmp_f = factor_tmp_1 * (in_f + in_f[1, 0, 0])
    factor_tmp_2 = 2.0
stage_2:
    factor_tmp_2 = 2.0
    out_f = factor_tmp_2 * (tmp_f + tmp_f[1, 0, 0])
```
However, if the iteration order is changed to `FORWARD`, the two stages have the following statements:
```
stage_1:
    factor_tmp_1 = 2.0
    tmp_f = factor_tmp_1 * (in_f + in_f[1, 0, 0])
    factor_tmp_2 = 2.0
stage_2:
    out_f = factor_tmp_2 * (tmp_f + tmp_f[1, 0, 0])
```
In this case, the second temporary field is not demoted back to a scalar and so the generated code is not correct.

The solution is treat all blocks the same regardless of iteration order in the `NormalizeBlocksPass.apply` method. The remaining transformation passes then ensure that the correct code is generated.

### CODE REVIEW

**Comment by havogt** [comment]
Is this a fix for #160?

**Comment by stubbiali** [comment]
Not sure @havogt. The example in #160 produces the same results irrespective of the iteration order (as it should be, since there isn't any vertical dependency).

**Comment by havogt** [comment]
Right, I was making the connection without carefully reading again the case of #160.

**Comment by eddie-c-davis** [comment]
Correct, this issue is independent of backend.

**Review by DropD — APPROVED** [review]
Thank you!

**Pull request merged**
