### PR TITLE
Disallow stage merging if candidate precedes

### PR DESCRIPTION
**Pull request by jdahm**
## Description

Disallow stage merging if candidate precedes.

## Requirements

Before submitting this PR, please make sure:

- [ ] The code builds cleanly without new errors or warnings
- [ ] The code passes all the existing tests
- [ ] If this PR adds a new feature, new tests have been added to test these
new features
- [ ] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by tehrengruber** [comment]
Can you elaborate on the need for this? I recently also stumbled upon this and reordering is actually fine as long as there are no dependencies (this reordering was implemented here: https://github.com/GridTools/gt4py/pull/242).

**Comment by jdahm** [comment]
@tehrengruber Sure. After careful debugging, without this fix. The following gtscript
```
    with computation(FORWARD):
        with interval(0, 1):
            bet = dm[0, 0, 0] - aa[0, 0, 1]
        with interval(1, None):
            bet = bet[0, 0, -1]
    with computation(FORWARD):
        with interval(0, 1):
            w = (dm * w1 + dt * pp[0, 0, 1]) / bet
        with interval(1, -2):
            gam = aa / bet[0, 0, -1]
            bet = dm - (aa + aa[0, 0, 1] + aa * gam)
            w = (dm * w1 + dt * (pp[0, 0, 1] - pp) - aa * w[0, 0, -1]) / bet
...
```
becomes this:
```

multi_stage__230: FORWARD
    stage__160:
        with interval(0, 1):
            bet = dm[0, 0, 0] - aa[0, 0, 1]

    stage__163:
        with interval(1, None):
            bet = bet[0, 0, -1]
        with interval(0, 1):
            w = (dm * w1 + dt * pp[0, 0, 1]) / bet

    stage__169:
        with interval(1, -2):
            gam = aa / bet[0, 0, -1]
            bet = dm - (aa + aa[0, 0, 1] + aa * gam)
            w = (dm * w1 + dt * (pp[0, 0, 1] - pp) - aa * w[0, 0, -1]) / bet
...
```

The problem is that ` stage__163` has ApplyBlocks that are out of order. That switched ordering in turn leads to an assertion in the code being triggered (in the numpy backend): https://github.com/GridTools/gt4py/blob/master/src/gt4py/backend/numpy_backend.py#L124

**Comment by jdahm** [comment]
This has at least some overlap with #242, and that seems like a better fix.￼ I will try that and follow up here.

**Comment by jdahm** [comment]
This seems no longer necessary.

**Pull request closed without merging**
