### PR TITLE
Dawn extent fix

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR fixes a bug in the field extent computations in the Dawn backends. The existing code is sufficient to pass the GT4Py test suite, but causes the compute domain to be too large for some FV3 stencils. The new generates more precise extents.

### CODE REVIEW

**Comment by DropD** [comment]
Please include a test which can be shown to fail before your changes. I am available to give guidance writing tests if necessary.

**Comment by eddie-c-davis** [comment]
Hello @DropD (love the name by the way), the line that highlights the need for this fix is at `src/gt4py/testing/suites.py:402`,
```python
assert all(
    field_info.boundary >= cls.global_boundaries[name]
    for name, field_info in implementation.field_info.items()
)
```
If the `>=` is changed to `==`, the Dawn backends will fail on the `TestHeatEquation_FTCS_3D` test (for example), because the code in master over-computes the boundaries for `u` and `v`, as `(2, 2), (0, 0), (0, 0))` and `(0,0), (2, 2), (0, 0))` but should be `(1, 1), (0, 0), (0, 0))` and `(0,0), (1, 1), (0, 0))`, respectively.

However, I realize such a global change may be undesirable, so where would you suggest to put a boundary size assertion inside the  `TestHeatEquation_FTCS_3D` test itself? Thank you.

**Comment by DropD** [comment]
One way would be to special-case right there in `gt4py.testing.suites`, since the name and type of the backend used are available. You could use something like `if issubclass(backend.from_name(implementation.backend), DawnBaseBackend)` or similar. and then apply the stricter `field_info.boundary == cls.global_boundaries[name]` test only to the dawn backends.

**Comment by eddie-c-davis** [comment]
Thank you for the recommendation Rico, this check has been implemented.

**Pull request merged**
