### PR TITLE
Adapt CI to ci-ext

### PR DESCRIPTION
**Pull request by finkandreas**
Use ci-ext service and simplified .gitlab-ci.yml for it.

### CODE REVIEW

**Comment by DropD** [comment]
cscs-ci run default

**Comment by havogt** [comment]
Can we get rid of Rico's face? 😜 Let me know if you need access to the gridtools github user.

**Comment by finkandreas** [comment]
@havogt Absolutely, you/Rico need to change the notification token, to a notification of the gridtools github user.

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
cscs-ci run

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
I have changed the notification token, so my face should be off the test results after the next run.

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
cscs-ci run default

**Comment by DropD** [comment]
superseeded by #1153 for convenience.

**Pull request closed without merging**
