### PR TITLE
fix[next]: DaCe CFG analysis -> remove structurally inaccessible states

### PR DESCRIPTION
**Pull request by kotsaloscv**
This workaround fixes [this DaCe issue](https://github.com/spcl/dace/issues/1625).

### CODE REVIEW

**Comment by edopao** [comment]
Just for me to understand a bit better why we have structurally inaccessible states.. which icon4py stencil is causing this issue?

**Comment by edopao** [comment]
> > Just for me to understand a bit better why we have structurally inaccessible states.. which icon4py stencil is causing this issue?
> 
> It is the [`calculate_enhanced_diffusion_coefficients_for_grid_point_cold_pools` in the Diffusion Granule](https://github.com/C2SM/icon4py/blob/f391bdb9c2ccb826768ddca0460c75d110d9daf2/model/atmosphere/diffusion/src/icon4py/model/atmosphere/diffusion/diffusion.py#L750C16-L750C83). I have also attached the SDFG for this specific stencil in the [DaCe issue](https://github.com/spcl/dace/issues/1625).

To me it looks like the SDFG is wrong: the start block of the NestedSDFG is undefined. Can you please try this other PR? https://github.com/GridTools/gt4py/pull/1599

**Comment by kotsaloscv** [comment]
> > > Just for me to understand a bit better why we have structurally inaccessible states.. which icon4py stencil is causing this issue?
> > 
> > 
> > It is the [`calculate_enhanced_diffusion_coefficients_for_grid_point_cold_pools` in the Diffusion Granule](https://github.com/C2SM/icon4py/blob/f391bdb9c2ccb826768ddca0460c75d110d9daf2/model/atmosphere/diffusion/src/icon4py/model/atmosphere/diffusion/diffusion.py#L750C16-L750C83). I have also attached the SDFG for this specific stencil in the [DaCe issue](https://github.com/spcl/dace/issues/1625).
> 
> To me it looks like the SDFG is wrong: the start block of the NestedSDFG is undefined. Can you please try this other PR? #1599

Indeed this fix works. I close this one and we merge your PR.

**Comment by kotsaloscv** [comment]
fix #1599

**Pull request closed without merging**
