### PR TITLE
Fix auto_sync_test to also succeed when run after other tests

### PR DESCRIPTION
**Pull request by gronerl**
Clear modified storages at start of test_auto_sync_storage
This should fix currently failing GPU CI.

### CODE REVIEW

**Comment by gronerl** [comment]
bors try

**Comment by gronerl** [comment]
bors try-
bors try

**Comment by gronerl** [comment]
bors try-
bors try

**Review by havogt — APPROVED** [review]
Looks good, once you win your fight against isort.

**Pull request merged**
