### PR TITLE
Constant Folding Pass

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR adds the `ConstantFolding` pass to the "classic" toolchain. The pass replaces all instances of temporaries that are only assigned once to a single scalar literal with that literal.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests
- [x] If this PR adds a new feature, new tests have been added to test these
new features
- [x] All relevant documentation has been updated or added

### CODE REVIEW

**Review by gronerl — CHANGES_REQUESTED** [review]
Consider this: 

```python
class TestConstantFolding(gt_testing.StencilTestSuite):

    dtypes = {("outfield",):np.float64,("cond",): np.float64}
    domain_range = [(1, 15), (2, 15), (1, 15)]
    backends = INTERNAL_BACKENDS_NAMES
    symbols = dict(
        outfield=gt_testing.field(in_range=(-10, 10), boundary=[(0, 0), (0, 0), (0, 0)]),
        cond=gt_testing.field(in_range=(-10, 10), boundary=[(0, 0), (0, 0), (0, 0)]),
    )

    def definition(outfield, cond):

        with computation(PARALLEL), interval(...):
            if cond != 0:
                tmp = 1
            outfield = tmp

    def validation(outfield, cond, *,domain, origin, **kwargs):
        outfield[np.array(cond, dtype=np.bool_)] = 1
```
Admittedly, `outfield` would here contain an undefined value where `cond` is not met, yet with your pass this would be always 1. This isn't much of an issue, but I think it would be safer to exclude this case.

**Comment by eddie-c-davis** [comment]
Thank you for the review and great catch @gronerl, the pass has been updated to consider if conditions.

**Comment by eddie-c-davis** [comment]
bors try

**Comment by gronerl** [comment]
bors try

**Review by gronerl — CHANGES_REQUESTED** [review]

**Comment by eddie-c-davis** [comment]
Thank you @gronerl, my apologies for missing the bad merge!

**Comment by gronerl** [comment]
Wait, why do tests pass both with and without the test change? Was this an artifact of the repeated call to your pass? If so, repeatedly calling would actually provide a benefit. (One of many great accidental discoveries? Pennicillin, Pospsicles and this Pass)

**Comment by gronerl** [comment]
but looks good now, thanks for this!

**Comment by eddie-c-davis** [comment]
It is an interesting result indeed. And like penicillin, a result of an error :-) Thank you for the review!

**Pull request merged**
