### PR TITLE
Update pre-commit hooks configs and related files

### PR DESCRIPTION
**Pull request by egparedes**
Update pre-commit hooks and source files according to the new checks.

Main changes:
- update versions of pre-commit hook repos
- remove encoding pragma from python files
- autoformat yaml files
- add checks for debug statements and merge conflicts inadvertently left in the sources

### CODE REVIEW

**Comment by DropD** [comment]
bors try

**Comment by DropD** [comment]
Note: CIGR faillure is due to the sarus / gitlab docker pull issue, not due to this PR.

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
I've created a bit of a mess with the history of this PR because I forced-push the commits but now it should be ok. The changes are now split in two commits: one with the (disabled) changes in the config, and one enabling the changes and updating all the files. I think we could merge this PR without squashing the two commits to simplify the integration of these changes into the working branches of other developers.

**Comment by egparedes** [comment]
bors try

**Comment by egparedes** [comment]
I had to force-push again because the `licenseheaders` hook was randomly modifying some files and thus I switched to a different one.

Additionally, the original idea of not squashing the commits is not possible, because in the current master there are different (wrong) versions of the headers, so it is needed to delete all of them by hand first and then apply the patch. Since it's not possible to have a commit in the history without licenses, all the commits in the PR could be squashed as usual.

**Comment by egparedes** [comment]
Closing this one and opening another one with other changes.

**Pull request closed without merging**
