### PR TITLE
Update dev tool configs

### PR DESCRIPTION
**Pull request by egparedes**
## Description

Main changes:
- tox (and affected CI configs): more sensible organization of environments using factors, better cache cleaning and using 4 processes for pytest
- flake8: added missing configuration (setup.cfg)
- flakehell (flake8 wrapper): added config (pyproject.toml)
- requirements-dev: added missing packages and useful pytest plugins (cache, xdist)

### CODE REVIEW

**Comment by egparedes** [comment]
bors try

**Comment by DropD** [comment]
bors try

**Review by DropD — APPROVED** [review]
Looks all good

**Comment by DropD** [comment]
Seems to speed up the CIGR runs quite a bit, roughly by factor 3, from 1:30 down to 0:30.

**Pull request merged**
