### PR TITLE
Format source option

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR adds a `format_source` option to the stencil decorator that allows the `black` formatting of generated python code to be disabled as a time saving measure.

### CODE REVIEW

**Review by egparedes — CHANGES_REQUESTED** [review]
This is a backend-specific feature for Python-based backends (debug and numpy) so it should not be implemented as a stencil decorator option but as a backend option in the affected backends.

The documentation in the Backend interface is not very clear (https://github.com/GridTools/gt4py/blob/6e3f99706618eaecc81e6a557934af1db6329b38/src/gt4py/backend/base.py#L70), so better take a look at examples in the Dawn backends: https://github.com/GridTools/gt4py/blob/6e3f99706618eaecc81e6a557934af1db6329b38/src/gt4py/backend/dawn_backends.py#L315 and https://github.com/GridTools/gt4py/blob/6e3f99706618eaecc81e6a557934af1db6329b38/src/gt4py/backend/dawn_backends.py#L646

The `versioning` field indicates if the option value should be included in the computation of the cache id for the compiled stencil, and thus the stencil will be recompiled if the value of this option changes (which it is probably the intended behavior here).

**Comment by eddie-c-davis** [comment]
Thank you @egparedes, this has been converted to a backend option.

**Comment by egparedes** [comment]
@eddie-c-davis, after reviewing again the PR, I realized that your first version was absolutely right and my suggestion was wrong :facepalm:  This is a bit embarrassing but I forgot that the source formating is applied to the Python module of the StencilObject subclass, not to the generated  .cpp files for the cpython extension, and therefore it affects all the backends.

Could you restore the first version of this PR? As soon as you just add the description of the new parameter in the docstring of the `stencil()` function in the `gtscript.py` file, I will accept it and merge straight away. I'm really sorry for the extra work :disappointed:

**Comment by eddie-c-davis** [comment]
No problem at all @egparedes, the original code has been restored.

**Review by egparedes — CHANGES_REQUESTED** [review]
It looks good.

**Pull request merged**
