### PR TITLE
Remove version switch for GridTools C++

### PR DESCRIPTION
**Pull request by havogt**
... since we only use GridTools v2.x now.

### CODE REVIEW

**Comment by havogt** [comment]
bors try

**Comment by havogt** [comment]
bors try-

**Review by gronerl — CHANGES_REQUESTED** [review]
The README.md needs an update as well.

**Comment by gronerl** [comment]
Daint has issues today.

**Comment by jdahm** [comment]
I like this. I wonder: could we simply remove the `gt_src_manager` altogether and use a submodule?

**Comment by havogt** [comment]
We are considering shipping GridTools via pip for functional, see https://github.com/GridTools/gridtools/pull/1720

**Comment by havogt** [comment]
bors try

**Comment by jdahm** [comment]
bors try

**Comment by jdahm** [comment]
@gronerl Can you re-review?

**Review by gronerl — APPROVED** [review]

**Comment by gronerl** [comment]
bors trz

**Comment by gronerl** [comment]
bors try

**Pull request merged**
