### PR TITLE
Add `device_sync` option to GTC GPU backends

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Description

This PR adds support for the `device_sync` backend option to the GTC GPU backends.

## Requirements

Before submitting this PR, please make sure:

- [x] The code builds cleanly without new errors or warnings
- [x] The code passes all the existing tests

### CODE REVIEW

**Comment by DropD** [comment]
bors try

**Comment by gronerl** [comment]
Let's make this a requriement for GPU backends!
Could you add a test like
```Python
@pytest.mark.parametrize('backend', GPU_BACKENDS)
def test_device_sync_option_registered(backend):
    backend_opts = gt4py.backend.from_name(backend).options
    assert 'device_sync' in backend_opts
    assert backend_opts['device_sync']['versioning']
    assert backend_opts['device_sync']['type'] is bool
```

**Comment by eddie-c-davis** [comment]
Will do!

**Comment by gronerl** [comment]
bors try

**Review by gronerl — APPROVED** [review]

**Pull request merged**
