### PR TITLE
Use unique arg index

### PR DESCRIPTION
**Pull request by havogt**
## Description

Proposed fix for #136.

## Requirements

Before submitting this PR, please make sure:

- [ ] The code builds cleanly without new errors or warnings
- [ ] The code passes all the existing tests
- [ ] If this PR adds a new feature, new tests have been added to test these
new features
- [ ] All relevant documentation has been updated or added

Additionally, if this PR contains code authored by new contributors:

- [ ] All the authors are covered by a valid contributor assignment agreement,
signed by the employer if needed, provided to ETH Zurich
- [ ] The names of all the new contributors have been added to an updated
version of the AUTHORS.rst file included in the PR

### CODE REVIEW

**Comment by egparedes** [comment]
Do we already know if the current way GridTools ids are generated is correct? If the generation is ok, would this PR be still useful for other reasons?

**Comment by havogt** [comment]
I think it's not needed, but I want to talk with Anton first. Let's keep it open, because at least moving temporaries up makes sense, I'd say.

**Comment by egparedes** [comment]
@havogt just pinging to see if this PR can be closed or it it should be updated and reviewed

**Comment by havogt** [comment]
I'd take the PR as it is.
From Anton:
>Global parameters are not special
> Args Indices for nontemporary fields must be unique within non temporaries. Args for temporaries must be unique within temporaries

So we need a fix for normal fields and global parameters, but temporaries could have their own index set. We can change the PR to reflect the minimum requirement or keep as it is, I have no preference.

**Comment by egparedes** [comment]
Ok, I think we can then merge the PR as it is.

**Pull request merged**
